version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: play
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: SECCURE12345
    ports:
      - "1306:3306"
  web:
    build: .
    volumes:
      - ./:/sampleService
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: sbt run