version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: play
  web:
    build: .
    volumes:
      - ./:/sampleService
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    command: sbt run